# Site settings
title: "Lê Quốc Dũng"
email: lqdung3@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chia sẽ mọi điều trong cuộc sống.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lqdungdt.github.io/lqdung" # the base hostname & protocol for your site

# Author information
author:
  name: "Lê Quốc Dũng, PhD"
  email: "lqdung3@gmail.com"
  bio: "Chia sẻ kiến thức trong cuộc sống."
  avatar: "/assets/images/avatar.PNG"
  location: "Vietnam"

# Social media
social:
  youtube: "https://youtube.com"
  instagram: "https://instagram.com"
  facebook: "https://facebook.com"
  email: "lqdung3@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  pages:
    output: true
    permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Lê Quốc Dũng"
  - scope:
      path: ""
    values:
      layout: "default"

# Pagination
paginate: 6
paginate_path: "/page:num/"

# SEO settings
lang: vi
locale: vi_VN

# Navigation
navigation:
  - name: "Trang chủ"
    link: "/"
  - name: "Bài viết"
    link: "/blog/"
  - name: "Giảng viên"
    link: "/lecture/"
  - name: "Nghiên cứu"
    link: "research"
  - name: "/Lưu niệm/"
    link: "/memory/"
  - name: "Liên hệ"
    link: "/contact/"

# Custom variables
brand:
  tagline: "Minimalist Solutions that Maximize Your Life"
  greeting: "Xin Chào!"
  greeting_text: >
    Cảm ơn bạn đã ghé thăm website của tôi.
    Đây là một chia sẻ những điều thú vị trong cuộc sống.

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Timezone
timezone: Asia/Ho_Chi_Minh
